import { assertProductionConfig } from './config.mjs';

assertProductionConfig();

const usingPostgres=Boolean(process.env.DATABASE_URL);
const driver=usingPostgres?await import('./postgres.mjs'):await import('./db.mjs');
if(driver.init)await driver.init();
export const storageDriver=usingPostgres?'postgresql':'sqlite';
export const getSession=(...args)=>Promise.resolve(driver.getSession(...args));
export const joinSession=(...args)=>Promise.resolve(driver.joinSession(...args));
export const controlSession=(...args)=>Promise.resolve(driver.controlSession(...args));
export const addResponse=(...args)=>Promise.resolve(driver.addResponse(...args));
export const authenticateUser=(...args)=>Promise.resolve(driver.authenticateUser(...args));
export const getAuthUser=(...args)=>Promise.resolve(driver.getAuthUser(...args));
export const revokeAuthSession=(...args)=>Promise.resolve(driver.revokeAuthSession(...args));
export const getWorkspace=(...args)=>Promise.resolve(driver.getWorkspace(...args));
export const updateOrganization=(...args)=>Promise.resolve(driver.updateOrganization(...args));
export const createWorkspaceMember=(...args)=>Promise.resolve(driver.createWorkspaceMember(...args));
export const updateWorkspaceMember=(...args)=>Promise.resolve(driver.updateWorkspaceMember(...args));
export const deleteWorkspaceMember=(...args)=>Promise.resolve(driver.deleteWorkspaceMember(...args));
export const moderateResponse=(...args)=>Promise.resolve(driver.moderateResponse(...args));
export const writeAudit=(...args)=>Promise.resolve(driver.writeAudit(...args));
export const getJoinCodeForSession=(...args)=>Promise.resolve(driver.getJoinCodeForSession(...args));
export const tickLiveSessions=(...args)=>Promise.resolve(driver.tickLiveSessions(...args));
export const listWorkshops=(...args)=>Promise.resolve(driver.listWorkshops(...args));
export const getWorkshop=(...args)=>Promise.resolve(driver.getWorkshop(...args));
export const createWorkshop=(...args)=>Promise.resolve(driver.createWorkshop(...args));
export const updateWorkshop=(...args)=>Promise.resolve(driver.updateWorkshop(...args));
export const deleteWorkshop=(...args)=>Promise.resolve(driver.deleteWorkshop(...args));
export const saveActivity=(...args)=>Promise.resolve(driver.saveActivity(...args));
export const deleteActivity=(...args)=>Promise.resolve(driver.deleteActivity(...args));
export const getReports=(...args)=>Promise.resolve(driver.getReports(...args));
export const getReportExportRows=(...args)=>Promise.resolve(driver.getReportExportRows(...args));
export const getAudience=(...args)=>Promise.resolve(driver.getAudience(...args));
export const createAudienceGroup=(...args)=>Promise.resolve(driver.createAudienceGroup(...args));
export const addAudiencePeople=(...args)=>Promise.resolve(driver.addAudiencePeople(...args));
export const listTemplates=(...args)=>Promise.resolve(driver.listTemplates(...args));
export const getTemplate=(...args)=>Promise.resolve(driver.getTemplate(...args));
export const createTemplate=(...args)=>Promise.resolve(driver.createTemplate(...args));
export const useTemplate=(...args)=>Promise.resolve(driver.useTemplate(...args));
export const deleteTemplate=(...args)=>Promise.resolve(driver.deleteTemplate(...args));
export const storageHealth=()=>driver.health?driver.health():Promise.resolve({driver:'sqlite'});
export const closeStorage=()=>driver.close?driver.close():Promise.resolve();
